# Generated by Django 5.1.1 on 2024-09-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deleted_at',
        ),
    ]
