version: '3'

services:
  smbot-postgres-compose:
    image: postgres:latest
    environment:
      POSTGRES_USER: smbot
      POSTGRES_PASSWORD: smbot
      POSTGRES_DB: custumers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  postgres_data:
