name: 🤖 ClientConnect Django Pipeline

on:
  push:
    branches:
      - main
      - stagging
  pull_request:
    branches:
      - main
      - stagging

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
    steps:
      - name: 🚀 Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        

      - name: 🔄 Run Migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          BACK_END_LOCAL_URL: ${{ secrets.BACK_END_LOCAL_URL }}
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          echo "Running migrations..."
          python manage.py migrate
        

      - name: 🧪 Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          BACK_END_LOCAL_URL: ${{ secrets.BACK_END_LOCAL_URL }}
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          echo "Running tests..."
          python manage.py test
        
