name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: custumers
          POSTGRES_USER: smbot
          POSTGRES_PASSWORD: smbot
        ports:
          - 5431:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para a versão mais recente

      - name: Set up Python
        uses: actions/setup-python@v5  # Atualizado para a versão mais recente
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
