name: Django CI

on:
  push:
    branches:
      - main
      - stagging
  pull_request:
    branches:
      - main
      - stagging

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - ${{ secrets.DB_PORT }}:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v5  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
