name: Django CI

on:
  push:
    branches:
      - main
      - stagging
  pull_request:
    branches:
      - main
      - stagging

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: custumers
          POSTGRES_USER: smbot
          POSTGRES_PASSWORD: smbot
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U smbot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v5  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:  
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DATABASE_URL: postgres://smbot:smbot@localhost:5432/custumers
        run: |
          python manage.py migrate

      - name: Run tests
        env:  
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DATABASE_URL: postgres://smbot:smbot@localhost:5432/custumers
        run: |
          python manage.py test
